#+AUTHOR: Jonatan Haltorp
#+AUTHOR: Jonathan Erlandsson

* git2web

** Prototypen
   Vi kan iterera över en branchs log genom följande kod. repo är ett
   `pygit2.repository.Repository-object`.

   ```python
master = repo.lookup_branch('master')
for logEntry in master.log():
    print(logEntry.commiter, logEntry.message, logEntry.oid_new, logEntry.oid_old)
   ```
   :note-jh: Flowchart för att bygga upp 'kartan' just nu skulle nog kunna
   fungera på det här viset:
   Repo -> branches
   branch -> log # <- detta ger oss lista över en branch's commits
   branch -> commit # via branch.get_object()
   commit -> diff # via commit.tree.diff_to_?
   diff -> stats # via diff.stats.{insertions, files_changed, deletions}
   diff -> patch # via diff.patch
   

** Utvecklingen
*** Libraries
    Generellt så tar python-modulen pygit2 in en dependency i form utav
    libgit2, utan libgit2 på systemet kommer `make venvprepare` inte fungera.
**** JS
     Fuck you reactjs, piece of shit idiot fuck.
     <3 angularjs
**** Python
     *Jinja2* kan vi använda för templating
     jinja docs: http://jinja.pocoo.org/docs/dev/intro/
     *pygit2* kan vi använda för att vrida & vända på ett git repo
     pygit2 docs: http://www.pygit2.org/

     :note-jh: jag har användt jinja när jag bloggat med jekyll, vet
     lite hur det fungerar. pygit2 vet jag inte hur det fungerar, men 
     det verkar iaf som man har ganska mycket kontrol över saker och ting.
     
** Frågetecken
    Frågor kring Organisation & resurser, dokumentation
** Mål

*** visualisera brancher & commits i grafer :TODO:
    :note-jh: Vi borde kunna göra det ganska enkelt via
    html5, canvas & grejer. Alternativt kan vi använda
    ett till 
    :TODO: gör en HTML5 prototyp för 
    
*** Använda git för VC :DONE:
*** Programmera i HTML, Javascript, CSS & Python
     CSS:  Bootstrap
     JS:   Anuglar.js
     Python: git2web, json 

*** Output :TODO:
**** JSON :TODO:
**** Markdown :OPTIONAL:
**** Statisk html :TODO:
     Fördel: snabbare än dynamiska sidor
     Specifikt Mål: Möjlighet att lägga in en hook då man commitar.
         
*** Visa olika tips kring hur man kan använda git :TODO: 
    :note-jh: Behöver specifieras mer.
