#+AUTHOR: Jonatan Haltorp
#+AUTHOR: Jonathan Erlandsson

* git2web
** Varför fungerar inte det här?
~~~
    <div ng-controller="repoCtrl as repos" class="container-fluid">
      <!-- This is the headcontainer. -->
      <nav class="navbar navbar-default">
	<div class="navbar-header">
	  <a class="navbar-brand">Git2Web</a>
	</div>
	<!-- :TODO: Add a dropdown menu for selecting the different branches -->
      </nav>
      <!--This is the Left containern. -->
      <div class="col-xs-12 col-md-6">
	<div ng-repeat="repo in repos.jsondata" class="row"> <!-- iterating div -->	  
	  <table class="table"> <!-- repo table -->
	    <h1 class="page-header"><a href="#" ng-click="repos.displayNewRepo(repo)">{{ repo }}</a></h1>
	    <tr ng-click="repos.branch=branch" ng-repeat="branch in repo">
	      <h3>{{ branch }}</h3>
	      <table ng-show="repos.branchSelected(branch)" class="table table-striped">
		<thead>
		  <th>Message</th>
		  <th>Commit</th>
		  <th>Author</th>
		</thead>
		<tbody>
		  <tr ng-click="repos.displayNewCommit(hash)" ng-repeat="(hash, commit) in branch">
		    <td>{{commit.message}}</td>
		    <td><code>{{hash}}</code></td>
		    <td>{{commit.author}}</td>
		  </tr>
		</tbody>
	      </table> <!-- commit table -->
	    </tr>
	  </table> <!-- repo table -->
	</div> <!-- iterating div -->
      </div>

      <!-- THis is the Right container. -->
      <div ng-show="repo.selected(repo.hash)" class="col-xs-12 col-md-6"> <!-- -->
	<!-- :TODO: Add a header here for the commit, with overall data like
	     total amount of lines deleted or inserted, parent commit
	     commit id, commit message, author & date??! -->
	<!-- This is the commit metadata container -->
	<div ng-repeat="meta in repo.commitMetadata" class="diff">
	  <dl class="dl-horizontal">
	    <dt><code>{{ meta.filename }}</code></dt>
	    <dd><code>{{ meta.hash }}</code></dd>
	  </dl>
	</div>
      </div> <!-- /right container -->

    </div> <!-- /row -->
~~~
** irc quotes
   <sandia> jonatanhal: varför vill den inte skriva ut texter... Slnger snart ut
   alla mina datorer och telefon från fönstret och går ut i bilen och
   kör över dom inte 1 gång utan 3 gånger och sen åker jag till affären
   och köper en ben and jerry och sen kör jag över datorerna igen
   ...
   <sandia> Jag kan göra grafer då slipper jag hålla på med javascripts jävla
   skti variablar. Så får jag gå till ett vettigt språk men jag ska dra
   till affären för det fanns ingen mat här inte ens frukost. och de
   säger inget itll mig..
   <@jonatanhal> det går bra för dig nu erland
** Prototypen
   Vi kan iterera över en branchs log genom följande kod. repo är ett
   `pygit2.repository.Repository-object`.

   ```python
master = repo.lookup_branch('master')
for logEntry in master.log():
    print(logEntry.commiter, logEntry.message, logEntry.oid_new, logEntry.oid_old)
   ```
   :note-jh: Flowchart för att bygga upp 'kartan' just nu skulle nog kunna
   fungera på det här viset:
   Repo -> branches
   branch -> log # <- detta ger oss lista över en branch's commits
   branch -> commit # via branch.get_object()
   commit -> diff # via commit.tree.diff_to_?
   diff -> stats # via diff.stats.{insertions, files_changed, deletions}
   diff -> patch # via diff.patch
   
** Utvecklingen
*** Libraries
    Generellt så tar python-modulen pygit2 in en dependency i form utav
    libgit2, utan libgit2 på systemet kommer `make venvprepare` inte fungera.
**** JS
     Fuck you reactjs, piece of shit idiot fuck.
     <3 angularjs
**** Python
     *Jinja2* kan vi använda för templating
     jinja docs: http://jinja.pocoo.org/docs/dev/intro/
     *pygit2* kan vi använda för att vrida & vända på ett git repo
     pygit2 docs: http://www.pygit2.org/

     :note-jh: jag har användt jinja när jag bloggat med jekyll, vet
     lite hur det fungerar. pygit2 vet jag inte hur det fungerar, men 
     det verkar iaf som man har ganska mycket kontrol över saker och ting.
     
** Frågetecken
    Frågor kring Organisation & resurser, dokumentation
** Mål

*** visualisera brancher & commits i grafer :TODO:
    :note-jh: Vi borde kunna göra det ganska enkelt via
    html5, canvas & grejer. Alternativt kan vi använda
    ett till 
    :TODO: gör en HTML5 prototyp för 
    
*** Använda git för VC :DONE:
*** Programmera i HTML, Javascript, CSS & Python
     CSS:  Bootstrap
     JS:   Anuglar.js
     Python: git2web, json 

*** Output :TODO:
**** JSON :TODO:
**** Markdown :OPTIONAL:
**** Statisk html :TODO:
     Fördel: snabbare än dynamiska sidor
     Specifikt Mål: Möjlighet att lägga in en hook då man commitar.
         
*** Visa olika tips kring hur man kan använda git :TODO: 
    :note-jh: Behöver specifieras mer.
